#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEVICES="wave_4b wave_35 wave_5 wave_43 crowpanel"
VERSION=$(tr -d '[:space:]' < "$REPO_ROOT/version.txt")

if [ -z "$VERSION" ]; then
    echo "Error: version.txt is empty"
    exit 1
fi

RELEASE_DIR="$REPO_ROOT/release/v${VERSION}"

echo "Building Kern v${VERSION} release for: ${DEVICES}"
echo "Output: ${RELEASE_DIR}"
echo

# Source ESP-IDF only if idf.py isn't already on PATH (matches justfile)
command -v idf.py >/dev/null || source ~/esp/esp-idf/export.sh

# Start clean: everything here is regenerated by this script + sign_release.sh;
# stale zips/signed images from a previous round must not look publishable
rm -rf "$RELEASE_DIR"
mkdir -p "$RELEASE_DIR"

cd "$REPO_ROOT"

for DEVICE in $DEVICES; do
    echo "========================================"
    echo "Building for ${DEVICE}..."
    echo "========================================"

    # Delegate to justfile so the SDKCONFIG/build-dir layout stays in one place
    just build "$DEVICE"

    BUILD_DIR="$REPO_ROOT/build_${DEVICE}"
    DEVICE_DIR="$RELEASE_DIR/${DEVICE}"
    mkdir -p "$DEVICE_DIR"

    # Stage the raw parts per device. The final artifacts (signed app,
    # NVS-preserving Intel HEX, zip) are produced by sign_release.sh on the
    # air-gapped signing PC — nothing packaged here would survive signing.
    cp "$BUILD_DIR/bootloader/bootloader.bin" "$DEVICE_DIR/"
    cp "$BUILD_DIR/partition_table/partition-table.bin" "$DEVICE_DIR/"
    cp "$BUILD_DIR/ota_data_initial.bin" "$DEVICE_DIR/"
    cp "$BUILD_DIR/kern.bin" "$DEVICE_DIR/firmware.bin"

    echo "${DEVICE} staged"
    echo
done

# Ship version + signing script with the release folder so the whole folder
# can be moved to the air-gapped signing PC via SD card
echo "$VERSION" > "$RELEASE_DIR/VERSION"
cp "$SCRIPT_DIR/sign_release.sh" "$RELEASE_DIR/"

echo "========================================"
echo "Release v${VERSION} complete!"
echo "Files in ${RELEASE_DIR}:"
ls -lh "$RELEASE_DIR"
