name: GitHub Actions test
on: [push]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format
    - name: Check formatting
      run: ./format.sh --check

  build:
    needs: format-check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v6.0
        target: esp32p4
        command: idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults" build all size-components size
